#!/bin/bash

# ------------------------------------------------------------------
# This script wraps docker-compose to provide environment based
# defaults and added functionality.
#
# Use it from the project root just like docker-composer
#
# example:
#
# scripts/dev up
# ------------------------------------------------------------------

# take a look to this file to learn more on the predefined
# environment variables and functions
source $(dirname "$0")/lib/init

# allow frontend and backend folders to be read by Dockerfile(s)
# make-dockerignore servicename

COMMON="-f docker-compose.yml -f docker-compose.dev.yml"

docker compose $COMMON "$@"
